version: 2

updates:
  - package-ecosystem: "docker"
    target-branch: "iroha2-dev"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    target-branch: "iroha2-dev"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    target-branch: "iroha2-dev"
    directory: "/"
    schedule:
      interval: "daily"
