version: "3"

services:
  iroha:
    image: hyperledger/iroha2:lts@sha256:4072d09bee376c8fcbc586d35ea25624738694ce2c37aa0db60c9998c613048b
    environment:
      TORII_P2P_ADDR: iroha:1337
      TORII_API_URL: iroha:8080
      TORII_TELEMETRY_URL: iroha:8180
      IROHA_PUBLIC_KEY: "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"
      IROHA_PRIVATE_KEY: '{"digest_function": "ed25519", "payload": "282ed9f3cf92811c3818dbc4ae594ed59dc1a2f78e4241e31924e101d6b1fb831c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}'
      SUMERAGI_TRUSTED_PEERS: '[{"address":"iroha:1337", "public_key": "ed01201c61faf8fe94e253b93114240394f79a607b7fa55f9e5a41ebec74b88055768b"}]'
      RUST_BACKTRACE: full
      MAX_LOG_LEVEL: INFO
      IROHA2_GENESIS_PATH: genesis.json
      IROHA2_CONFIG_PATH: config.json
    ports:
      - "8080:8080"
      - "8180:8180"
    volumes:
      - "../modules/testcontainers/src/main/resources/genesis.json:/genesis.json"
      - "../modules/testcontainers/src/main/resources/config.json:/config.json"
    command: ./iroha --submit-genesis
