name: Iroha2-java main branch workflow

on:
  push:
    branches: [ iroha2-dev, iroha2-main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        library:
          - client
          - model
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build
    # - name: Generate list of libs
    #   run: ls ./modules/**/*.jar 
    #   run: echo "{ libs_list } = {  }" >> $GITHUB_ENV
    - name: Publish lib to nexus for branch
      if: ${{ github.ref == 'refs/heads/iroha2-dev' }}
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://nexus.iroha.tech/
        username: '${{ secrets.NEXUS_USER }}'
        password: '${{ secrets.NEXUS_PASS }}'
        format: maven2
        repository: maven-soramitsu
        coordinates: groupId=jp.co.soramitsu.iroha2-java artifactId={{ matrix.library }} version=${{ github.sha }}
        assets: extension=jar
        filename: ./modules/{{ matrix.library }}/build/libs/{{ matrix.library }}-1.0-SNAPSHOT.jar
